// res.data.results

module.exports = [
  {
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
    name: "Singapore",
    photos: [[Object]],
    place_id: "ChIJyY4rtGcX2jERIKTarqz3AAQ",
    reference: "ChIJyY4rtGcX2jERIKTarqz3AAQ",
    scope: "GOOGLE",
    types: ["locality", "political"],
    vicinity: "Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
    name: "Changi Bethany Kindergarten",
    place_id: "ChIJjdcqcN882jERdq1-Dhmpqns",
    plus_code: {
      compound_code: "8XR6+MM Singapore",
      global_code: "6PH58XR6+MM",
    },
    rating: 1,
    reference: "ChIJjdcqcN882jERdq1-Dhmpqns",
    scope: "GOOGLE",
    types: ["school", "point_of_interest", "establishment"],
    user_ratings_total: 1,
    vicinity: "694 Upper Changi Road East",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/worship_general-71.png",
    name: "Changi Bethany Church",
    photos: [[Object]],
    place_id: "ChIJXyGdcd882jERqYxjINHglTQ",
    plus_code: {
      compound_code: "8XR6+MQ Singapore",
      global_code: "6PH58XR6+MQ",
    },
    rating: 4,
    reference: "ChIJXyGdcd882jERqYxjINHglTQ",
    scope: "GOOGLE",
    types: ["church", "place_of_worship", "point_of_interest", "establishment"],
    user_ratings_total: 2,
    vicinity: "694 Upper Changi Road East",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "Onhand Industrial & Trading",
    place_id: "ChIJ02lujN882jERsDcpxLyYi0A",
    plus_code: {
      compound_code: "8XV6+7F Singapore",
      global_code: "6PH58XV6+7F",
    },
    reference: "ChIJ02lujN882jERsDcpxLyYi0A",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "20 Jalan Pergam",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "SUTD Fabrication Lab",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJnQukGt882jERY6JiOyjiVNE",
    plus_code: {
      compound_code: "8XR7+J6 Singapore",
      global_code: "6PH58XR7+J6",
    },
    rating: 4.7,
    reference: "ChIJnQukGt882jERY6JiOyjiVNE",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    user_ratings_total: 6,
    vicinity: "53B Somapah Road, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/cafe-71.png",
    name: "gomgom, Sandwiches/Subs",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJvTg_Od882jERRCXjPUeQVtQ",
    plus_code: {
      compound_code: "8XR7+72 Singapore",
      global_code: "6PH58XR7+72",
    },
    price_level: 1,
    rating: 4.4,
    reference: "ChIJvTg_Od882jERRCXjPUeQVtQ",
    scope: "GOOGLE",
    types: ["cafe", "food", "point_of_interest", "establishment"],
    user_ratings_total: 39,
    vicinity: "8 Somapah Road, #01-202A, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bank-71.png",
    name: "DBS SUTD Branch 24/7 Self-Service Branch",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJuQrnSN882jERRV7VmACIXN4",
    plus_code: {
      compound_code: "8XR6+5V Singapore",
      global_code: "6PH58XR6+5V",
    },
    rating: 3,
    reference: "ChIJuQrnSN882jERRV7VmACIXN4",
    scope: "GOOGLE",
    types: ["bank", "atm", "finance", "point_of_interest", "establishment"],
    user_ratings_total: 16,
    vicinity: "8 Somapah Road, #01-103",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png",
    name: "SUTD Canteen",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJ7wEVGN882jERpLUCf07L16U",
    plus_code: {
      compound_code: "8XR7+96 Singapore",
      global_code: "6PH58XR7+96",
    },
    rating: 3.4,
    reference: "ChIJ7wEVGN882jERpLUCf07L16U",
    scope: "GOOGLE",
    types: ["food", "point_of_interest", "establishment"],
    user_ratings_total: 309,
    vicinity: "8 Somapah Road, #02-201 Building 2, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "Richrij Management Pte Ltd",
    place_id: "ChIJqzcI7N882jERQTkZSjQptX0",
    plus_code: {
      compound_code: "8XV6+FQ Singapore",
      global_code: "6PH58XV6+FQ",
    },
    reference: "ChIJqzcI7N882jERQTkZSjQptX0",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "715 Upper Changi Road East",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
    name: "Singapore University of Technology and Design",
    photos: [[Object]],
    place_id: "ChIJy2Dymdg82jERGFUCbbzKvpk",
    plus_code: {
      compound_code: "8XR7+G8 Singapore",
      global_code: "6PH58XR7+G8",
    },
    rating: 4.6,
    reference: "ChIJy2Dymdg82jERGFUCbbzKvpk",
    scope: "GOOGLE",
    types: ["university", "point_of_interest", "establishment"],
    user_ratings_total: 258,
    vicinity: "8 Somapah Road",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "lliveo",
    opening_hours: { open_now: true },
    place_id: "ChIJhaOANt882jERYsfh8J0QDMI",
    plus_code: {
      compound_code: "8XR6+3X Singapore",
      global_code: "6PH58XR6+3X",
    },
    reference: "ChIJhaOANt882jERYsfh8J0QDMI",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "8 Somapah Road, Building 1, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
    name: "The Bioinspired & Integrative Science Lab",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJHz-ENt882jERpss1fUdZSy8",
    plus_code: {
      compound_code: "8XR6+3X Singapore",
      global_code: "6PH58XR6+3X",
    },
    rating: 5,
    reference: "ChIJHz-ENt882jERpss1fUdZSy8",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    user_ratings_total: 1,
    vicinity: "Building 1, #02-209,, 8 Somapah Road, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
    name: "Lee Kuan Yew Centre for Innovative Cities",
    photos: [[Object]],
    place_id: "ChIJrzd0kVka2jER36188l3YS8c",
    plus_code: {
      compound_code: "8XR6+3X Singapore",
      global_code: "6PH58XR6+3X",
    },
    rating: 5,
    reference: "ChIJrzd0kVka2jER36188l3YS8c",
    scope: "GOOGLE",
    types: ["university", "point_of_interest", "establishment"],
    user_ratings_total: 3,
    vicinity: "8 Somapah Road, Level 2, Building 3",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "SUTD Staff Housing",
    photos: [[Object]],
    place_id: "ChIJCbe-qt882jERZeiQcNPcNVg",
    plus_code: {
      compound_code: "8XR7+W9 Singapore",
      global_code: "6PH58XR7+W9",
    },
    reference: "ChIJCbe-qt882jERZeiQcNPcNVg",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "51 Changi South Avenue 1, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png",
    name: "SUTD Library",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJM6c6MN882jERSX5StXrTBHI",
    plus_code: {
      compound_code: "8XR7+55 Singapore",
      global_code: "6PH58XR7+55",
    },
    rating: 4.7,
    reference: "ChIJM6c6MN882jERSX5StXrTBHI",
    scope: "GOOGLE",
    types: ["library", "point_of_interest", "establishment"],
    user_ratings_total: 15,
    vicinity: "8 Somapah Road, Building 1, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/atm-71.png",
    name: "DBS ATM",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: "ChIJyT5KPt882jERHpeccX2983s",
    plus_code: {
      compound_code: "8XR7+99 Singapore",
      global_code: "6PH58XR7+99",
    },
    reference: "ChIJyT5KPt882jERHpeccX2983s",
    scope: "GOOGLE",
    types: ["atm", "finance", "point_of_interest", "establishment"],
    vicinity: "8 Somapah Road, #01-103 Building 1, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/school-71.png",
    name: "SUTD One-Stop Centre",
    opening_hours: { open_now: true },
    place_id: "ChIJV4rpJd882jERvcYb_bF3gQ4",
    plus_code: {
      compound_code: "8XR7+78 Singapore",
      global_code: "6PH58XR7+78",
    },
    rating: 5,
    reference: "ChIJV4rpJd882jERvcYb_bF3gQ4",
    scope: "GOOGLE",
    types: ["school", "point_of_interest", "establishment"],
    user_ratings_total: 2,
    vicinity: "6 Somapah Road, Singapore",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "Font Creative",
    place_id: "ChIJx8tE5t882jERsv-nvIoESYY",
    plus_code: {
      compound_code: "8XV6+JR Singapore",
      global_code: "6PH58XV6+JR",
    },
    reference: "ChIJx8tE5t882jERsv-nvIoESYY",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "723 Upper Changi Road East",
  },
  {
    business_status: "OPERATIONAL",
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
    name: "Financial Help for Single Mother",
    place_id: "ChIJyT9qWiA92jERQDjJRQRnd5M",
    plus_code: {
      compound_code: "8XV5+3F Singapore",
      global_code: "6PH58XV5+3F",
    },
    reference: "ChIJyT9qWiA92jERQDjJRQRnd5M",
    scope: "GOOGLE",
    types: ["point_of_interest", "establishment"],
    vicinity: "168B Simei Lane",
  },
  {
    geometry: { location: [Object], viewport: [Object] },
    icon: "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
    name: "Tampines",
    photos: [[Object]],
    place_id: "ChIJ0e4CNAQ92jERy_T_mqOSB48",
    reference: "ChIJ0e4CNAQ92jERy_T_mqOSB48",
    scope: "GOOGLE",
    types: ["neighborhood", "political"],
    vicinity: "Singapore",
  },
];
